name: 'Rasa NLU Benchmark'
description: 'Runs a Rasa server and benchmarks a given Rasa NLU model'
inputs:
  rasa_project_path:
    description: 'Path to the Rasa project top level folder containing the poetry pyproject.toml file'
    required: true
  model_path:
    description: 'Path to the Rasa NLU model relative to rasa_project_path or absolute path'
    required: true
  duckling_url:
    description: 'URL of the Duckling server'
    required: false
  test_data_path:
    description: 'Path to the test data'
    required: true
  gar_token:
    description: 'Token for the GAR repository'
    required: true
  output_path:
    description: 'Path to the output file'
    required: false
  rasa_port:
    description: 'Port for the Rasa server'
    required: false
    default: '8005'
  gke_sa_key:
    description: 'Service account key for GKE'
    required: false
    default: ''
  threshold:
    description: 'Threshold for the benchmark'
    required: false
    default: '0.9'
outputs:
  time:
    description: 'The time the benchmark completed'
    value: ${{ steps.auth.outputs.time }}
runs:
  using: 'composite'
  steps:
    - name: Checkout target repo
      uses: actions/checkout@v4
      with:
        path: target-repo
    - name: Start Rasa server
      working-directory: ${{inputs.rasa_project_path}}
      shell: bash
      run: |
        poetry run rasa run --enable-api --model "${{inputs.model_path}}" --port "${{inputs.rasa_port}}" &

    - name: Install benchmark tool dependencies
      shell: bash
      run: |
        pip install -r ${{github.action_path}}/requirements.txt

    - name: Wait for Rasa Server and run benchmark
      shell: bash
      run: |
        echo "Running benchmark"
        python ${{github.action_path}}/benchmark/main.py --threshold "${{inputs.threshold}}" --nlu-data "${{github.workspace}}/target-repo/${{inputs.test_data_path}}"
        COMPLETION_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        echo "time=$COMPLETION_TIME" >> $GITHUB_OUTPUT
        pkill -f "rasa run"
