name: 'Rasa NLU Benchmark'
description: 'Runs a Rasa server and benchmarks a given Rasa NLU model'
inputs:
  model_path:
    description: 'Path to the Rasa NLU model'
    required: true
  duckling_url:
    description: 'URL of the Duckling server'
    required: true
  test_data_path:
    description: 'Path to the test data'
    required: true
  gar_token:
    description: 'Token for the GAR repository'
    required: true
  output_path:
    description: 'Path to the output file'
    required: false
  rasa_port:
    description: 'Port for the Rasa server'
    required: false
    default: '8005'
  gke_sa_key:
    description: 'Service account key for GKE'
    required: false
    default: ''
  threshold:
    description: 'Threshold for the benchmark'
    required: false
    default: '0.9'
outputs:
  time:
    description: 'The time the benchmark completed'
    value: ${{ steps.auth.outputs.time }}
runs:
  using: 'composite'
  steps:
    - name: Checkout target repo
      uses: actions/checkout@v4
      with:
        path: target-repo
    - name: Authenticate with Google Cloud
      id: 'auth'
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ inputs.gke_sa_key }}
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      # ------------------------------------------------------------------------------------------------ #
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.15
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install setuptools==65.5.1
        pip install wheel==0.44.0
        pip install rasa==3.6.20
        pip install spacy==3.7.0
        pip install packaging==22.0
        pip install git+https://github.com/die-lautmaler/rasa_components.git
        pip uninstall packaging -y
        pip install packaging==22.0
        pip install de-pipeline-lautmaler==1.1.1 --extra-index-url=https://oauth2accesstoken:${{ inputs.gar_token }}@europe-west3-python.pkg.dev/lautmaler-cca/cca-py/simple/
    - name: Start Rasa server
      shell: bash
      run: |
        pip uninstall packaging -y
        pip install packaging==21.0
        rasa run --enable-api --model "${{ inputs.model_path }}" --port "${{ inputs.rasa_port }}" &
        sleep 300
    - name: Run benchmark
      shell: bash
      run: |
        python -m pip install -r ${{ github.action_path }}/requirements.txt
        python ${{ github.action_path }}/benchmark/main.py --threshold "${{inputs.threshold}}" --nlu-data-dir "${{ github.workspace }}/target-repo/${{ inputs.test_data_path }}"
        COMPLETION_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        echo "time=$COMPLETION_TIME" >> $GITHUB_OUTPUT
        pkill -f "rasa run"