name: 'Rasa NLU Benchmark'
description: 'Runs a Rasa server and benchmarks a given Rasa NLU model'
inputs:
  model_path:
    description: 'Path to the Rasa NLU model'
    required: true
  duckling_url:
    description: 'URL of the Duckling server'
    required: true
  test_data_path:
    description: 'Path to the test data'
    required: true
  gar_token:
    description: 'Token for the GAR repository'
    required: true
  output_path:
    description: 'Path to the output file'
    required: false
  rasa_port:
    description: 'Port for the Rasa server'
    required: false
    default: '5005'
  gke_sa_key:
    description: 'Service account key for GKE'
    required: false
    default: ''
  threshold:
    description: 'Threshold for the benchmark'
    required: false
    default: '0.9'
outputs:
  time:
    description: 'The time the benchmark completed'
    value: ${{ steps.auth.outputs.time }}
runs:
  using: 'composite'
  steps:
    - name: Authenticate with Google Cloud
      id: 'auth'
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ inputs.gke_sa_key }}
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      # ------------------------------------------------------------------------------------------------ #
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.15
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools
        python -m pip install rasa==3.6.20
        python -m pip install spacy==3.7.0
        pip install git+https://github.com/die-lautmaler/rasa_components.git
        pip uninstall build
        pip install de-pipeline-lautmaler==1.1.1 --extra-index-url=https://oauth2accesstoken:${{ inputs.gar_token }}@europe-west3-python.pkg.dev/lautmaler-cca/cca-py/simple/
        chmod +x entrypoint.sh
    - name: Start bash script with variables
      shell: bash
      run: entrypoint.sh
      env:
        MODEL_PATH: ${{ inputs.model_path }}
        DUCKLING_URL: ${{ inputs.duckling_url }}
        TEST_DATA_PATH: ${{ inputs.test_data_path }}
        OUTPUT_PATH: ${{ inputs.output_path }}
        RASA_PORT: ${{ inputs.rasa_port }}
        GAR_TOKEN: ${{ inputs.gar_token }}
        GOOGLE_CREDENTIALS_JSON: ${{ inputs.gke_sa_key }}
        THRESHOLD: ${{ inputs.threshold }}