name: 'Rasa NLU Benchmark'
description: 'Runs a Rasa server and benchmarks a given Rasa NLU model'
inputs:
  model_path:
    description: 'Path to the Rasa NLU model'
    required: true
  duckling_url:
    description: 'URL of the Duckling server'
    required: true
  test_data_path:
    description: 'Path to the test data'
    required: true
  gar_token:
    description: 'Token for the GAR repository'
    required: true
  output_path:
    description: 'Path to the output file'
    required: false
  rasa_port:
    description: 'Port for the Rasa server'
    required: false
    default: '5005'
outputs:
  time:
    description: 'The time the benchmark completed'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    MODEL_PATH: ${{ inputs.model_path }}
    DUCKLING_URL: ${{ inputs.duckling_url }}
    TEST_DATA_PATH: ${{ inputs.test_data_path }}
    OUTPUT_PATH: ${{ inputs.output_path }}
    RASA_PORT: ${{ inputs.rasa_port }}
    GAR_TOKEN: ${{ inputs.gar_token }}